### ISSUE TITLE
About pip install -r requirements.txt

### ISSUE THREAD

**Issue by S1lHao** [razla/I-See-Dead-People-Gray-Box-Adversarial-Attack-on-Image-To-Text-Models#1]
There are no suitable versions for install, nvidia-nccl-cu11, and Triton in the requirements. txt file, and is there really an install library (line 77)? And there are torch files in the git repositories you referenced, do we still need to install torch files at the end?

**Comment by razla** [comment]
You don't need Triton - only torch and huggingface.

**Comment by S1lHao** [comment]
> 你不需要 Triton - 只需要火炬和拥抱脸。

Could you please provide the corresponding version？ And which CUDA version do you use?

**Comment by razla** [comment]
You can leave Triton - there's no need for this package.
Torch Version: 2.1.2
CUDA Version: 12.4

**Comment by S1lHao** [comment]
> 您可以离开 Triton - 不需要此软件包。 Torch 版本：2.1.2 CUDA 版本：12.4

Thank you
